name = "crowdflowworkers"
compatibility_date = "2023-01-01"

# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "crowdflow-testing"
database_id = "d6ec5f68-8ac4-4b66-a8c6-3bb336058890"
